# comments.py
# THIS FILE IS AUTOMATICALLY GENERATED FROM comments.pil.
# DO NOT EDIT!

"""This is a single-line triple-double-quote comment."""

"""This is a
multi-line
triple-double-quote
comment,
with the quotes on the same lines as the text."""

"""
This is a multi-line
triple-double-quote
comment, with the quotes
on different lines than
the text.
"""

"""This is a triple-double-quote
comment"""
