# simple_class.py
# THIS FILE IS AUTOMATICALLY GENERATED FROM comments.pil.
# DO NOT EDIT!

class square:
        def __init__(self, length):
		self._length = length
	def area(self):
		return self._length ** 2

mysquare = square(5)
area = mysquare.area()
print(area)

mysquare = square(5)
print(mysquare.area())
